"""Invitaciones a metas con aceptacion

Revision ID: 0e5edd5c7187
Revises: 0fde2d80d696
Create Date: 2026-08-27 21:26:28.842659

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0e5edd5c7187'
down_revision = '0fde2d80d696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitaciones_quest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('invitado_por_id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=512), nullable=False),
    sa.Column('correo_bi', sa.String(length=64), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='pendiente', nullable=False),
    sa.Column('respondida_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invitado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quest_id', 'correo_bi', 'estado', name='uq_invitacion_viva')
    )
    with op.batch_alter_table('invitaciones_quest', schema=None) as batch_op:
        batch_op.create_index('ix_invitaciones_correo_bi', ['correo_bi'], unique=False)
        batch_op.create_index('ix_invitaciones_quest', ['quest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitaciones_quest_correo_bi'), ['correo_bi'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitaciones_quest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitaciones_quest_correo_bi'))
        batch_op.drop_index('ix_invitaciones_quest')
        batch_op.drop_index('ix_invitaciones_correo_bi')

    op.drop_table('invitaciones_quest')
    # ### end Alembic commands ###
