"""Sesiones con refresh token revocable

Revision ID: 0fde2d80d696
Revises: a88ee205c181
Create Date: 2026-08-27 21:22:34.803164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fde2d80d696'
down_revision = 'a88ee205c181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('dispositivo', sa.String(length=120), nullable=True),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultimo_uso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_revocacion', sa.String(length=30), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sesiones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesiones_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index('ix_sesiones_usuario', ['usuario_id'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_version', sa.Integer(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('token_version')

    with op.batch_alter_table('sesiones', schema=None) as batch_op:
        batch_op.drop_index('ix_sesiones_usuario')
        batch_op.drop_index(batch_op.f('ix_sesiones_token_hash'))

    op.drop_table('sesiones')
    # ### end Alembic commands ###
