"""Categorias de gasto por usuario

Revision ID: 2a871b025b3d
Revises: d789cc46cdde
Create Date: 2026-08-28 19:14:00.510473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a871b025b3d'
down_revision = 'd789cc46cdde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias_gasto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('categorias_gasto_nombre_key'), type_='unique')
        batch_op.create_index('ix_categorias_usuario', ['usuario_id'], unique=False)
        batch_op.create_unique_constraint('uq_categoria_por_usuario', ['usuario_id', 'nombre'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias_gasto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_categoria_por_usuario', type_='unique')
        batch_op.drop_index('ix_categorias_usuario')
        batch_op.create_unique_constraint(batch_op.f('categorias_gasto_nombre_key'), ['nombre'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
