"""Esquema inicial de QuestCash

Revision ID: 4ade5fbf7c00
Revises: 
Create Date: 2026-08-27 20:20:17.080923

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4ade5fbf7c00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('insignias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('rareza', sa.String(length=20), nullable=False),
    sa.Column('icono', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=512), nullable=False),
    sa.Column('correo', sa.String(length=512), nullable=False),
    sa.Column('correo_bi', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('puntos_totales', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=512), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('notif_ia', sa.Boolean(), nullable=False),
    sa.Column('notif_fechas', sa.Boolean(), nullable=False),
    sa.Column('notif_progreso', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_correo_bi'), ['correo_bi'], unique=True)

    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=1024), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=30), nullable=True),
    sa.Column('es_hormiga', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_gasto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('monto_objetivo', sa.Float(), nullable=False),
    sa.Column('monto_actual', sa.Float(), nullable=False),
    sa.Column('fecha_limite', sa.Date(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('dificultad', sa.String(length=20), nullable=True),
    sa.Column('estatus', sa.String(length=20), nullable=False),
    sa.Column('puntos_recompensa', sa.Integer(), nullable=False),
    sa.Column('puntos_otorgados', sa.Boolean(), nullable=False),
    sa.Column('es_colaborativo', sa.Boolean(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('icono', sa.String(length=30), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_insignias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('insignia_id', sa.Integer(), nullable=False),
    sa.Column('fecha_obtenida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['insignia_id'], ['insignias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'insignia_id', name='uq_usuario_insignia')
    )
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('nota', sa.String(length=2048), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('icono', sa.String(length=30), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participaciones_quest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('fecha_union', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'quest_id', name='uq_usuario_quest')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participaciones_quest')
    op.drop_table('notificaciones')
    op.drop_table('movimientos')
    op.drop_table('usuarios_insignias')
    op.drop_table('quests')
    op.drop_table('gastos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_correo_bi'))

    op.drop_table('usuarios')
    op.drop_table('insignias')
    op.drop_table('categorias_gasto')
    # ### end Alembic commands ###
