"""Marcas de tiempo e indices de consulta

Revision ID: a88ee205c181
Revises: a66913af150d
Create Date: 2026-08-27 20:29:35.306897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88ee205c181'
down_revision = 'a66913af150d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias_gasto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.create_index('ix_gastos_categoria', ['categoria_id'], unique=False)
        batch_op.create_index('ix_gastos_usuario_fecha', ['usuario_id', sa.literal_column('fecha DESC')], unique=False)

    with op.batch_alter_table('insignias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.create_index('ix_movimientos_quest', ['quest_id'], unique=False)
        batch_op.create_index('ix_movimientos_usuario_fecha', ['usuario_id', sa.literal_column('fecha DESC')], unique=False)

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.create_index('ix_notificaciones_usuario_fecha', ['usuario_id', sa.literal_column('fecha_creacion DESC')], unique=False)

    with op.batch_alter_table('participaciones_quest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.create_index('ix_participaciones_quest', ['quest_id'], unique=False)

    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.create_index('ix_quests_usuario', ['usuario_id'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('usuarios_insignias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.create_index('ix_usuarios_insignias_insignia', ['insignia_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios_insignias', schema=None) as batch_op:
        batch_op.drop_index('ix_usuarios_insignias_insignia')
        batch_op.drop_column('actualizado_en')
        batch_op.drop_column('creado_en')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('actualizado_en')
        batch_op.drop_column('creado_en')

    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index('ix_quests_usuario')
        batch_op.drop_column('actualizado_en')
        batch_op.drop_column('creado_en')

    with op.batch_alter_table('participaciones_quest', schema=None) as batch_op:
        batch_op.drop_index('ix_participaciones_quest')
        batch_op.drop_column('actualizado_en')
        batch_op.drop_column('creado_en')

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_index('ix_notificaciones_usuario_fecha')
        batch_op.drop_column('actualizado_en')
        batch_op.drop_column('creado_en')

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.drop_index('ix_movimientos_usuario_fecha')
        batch_op.drop_index('ix_movimientos_quest')
        batch_op.drop_column('actualizado_en')
        batch_op.drop_column('creado_en')

    with op.batch_alter_table('insignias', schema=None) as batch_op:
        batch_op.drop_column('actualizado_en')
        batch_op.drop_column('creado_en')

    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.drop_index('ix_gastos_usuario_fecha')
        batch_op.drop_index('ix_gastos_categoria')
        batch_op.drop_column('actualizado_en')
        batch_op.drop_column('creado_en')

    with op.batch_alter_table('categorias_gasto', schema=None) as batch_op:
        batch_op.drop_column('actualizado_en')
        batch_op.drop_column('creado_en')

    # ### end Alembic commands ###
