"""Claves de idempotencia

Revision ID: b8392c26ed16
Revises: 0e5edd5c7187
Create Date: 2026-08-27 21:33:37.042599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8392c26ed16'
down_revision = '0e5edd5c7187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claves_idempotencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.String(length=120), nullable=False),
    sa.Column('codigo_http', sa.Integer(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'endpoint', 'clave', name='uq_idempotencia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claves_idempotencia')
    # ### end Alembic commands ###
