"""Tokens de correo de un solo uso

Revision ID: d407e2a72bf4
Revises: b8392c26ed16
Create Date: 2026-08-28 18:28:49.751129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd407e2a72bf4'
down_revision = 'b8392c26ed16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens_correo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_solicitud', sa.String(length=45), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens_correo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_correo_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index('ix_tokens_correo_usuario', ['usuario_id', 'tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens_correo', schema=None) as batch_op:
        batch_op.drop_index('ix_tokens_correo_usuario')
        batch_op.drop_index(batch_op.f('ix_tokens_correo_token_hash'))

    op.drop_table('tokens_correo')
    # ### end Alembic commands ###
